---

- name: CI pipeline to inegerate registration service
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Displaying Starting Message
      debug:
        msg: "Ci Pipeline for registration service, is starting"

    - name: Apply Page Template
      template:
        src: files/env-template.j2
        dest: /var/tmp/env-template.yaml

    - name: Download Apache tarball file
      shell: kubectl apply -f env-template.yaml
      args:
        chdir: /var/tmp
        warn: false
