---

- name: CI pipeline to inegerate registration service
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Displaying Starting Message
      debug:
        msg: "Ci Pipeline for registration service, is starting"

    - name: Gradle Build
      ansible.builtin.shell: gradle clean build -x test
      args:
        chdir: /home/janitha/ws/CMM707/registration-service/registration-service/

    - name: Building and pushing docker image to the DockerHub
      ansible.builtin.shell: gradle jib -x test
      args:
        chdir: /home/janitha/ws/CMM707/registration-service/registration-service/
