---

- name: Runbook to Deploy Environments
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: Displaying Starting Message
      debug:
        msg: "Deploying {{ branch }} in the {{ env_name }}"

    - name: Creating Application
      template:
        src: files/env-template.j2
        dest: /var/tmp/env-template.yaml

    - name: Deploying Application
      shell: kubectl apply -f env-template.yaml
      args:
        chdir: /var/tmp
        warn: false
